export const livrosBiblia = [
  // Antigo Testamento
  { id: "genesis", nome: "Gênesis", nomeIngles: "genesis", capitulos: 50 },
  { id: "exodus", nome: "Êxodo", nomeIngles: "exodus", capitulos: 40 },
  { id: "leviticus", nome: "Levítico", nomeIngles: "leviticus", capitulos: 27 },
  { id: "numbers", nome: "Números", nomeIngles: "numbers", capitulos: 36 },
  {
    id: "deuteronomy",
    nome: "Deuteronômio",
    nomeIngles: "deuteronomy",
    capitulos: 34,
  },
  { id: "joshua", nome: "Josué", nomeIngles: "joshua", capitulos: 24 },
  { id: "judges", nome: "Juízes", nomeIngles: "judges", capitulos: 21 },
  { id: "ruth", nome: "Rute", nomeIngles: "ruth", capitulos: 4 },
  { id: "1-samuel", nome: "1 Samuel", nomeIngles: "1 samuel", capitulos: 31 },
  { id: "2-samuel", nome: "2 Samuel", nomeIngles: "2 samuel", capitulos: 24 },
  { id: "1-kings", nome: "1 Reis", nomeIngles: "1 kings", capitulos: 22 },
  { id: "2-kings", nome: "2 Reis", nomeIngles: "2 kings", capitulos: 25 },
  {
    id: "1-chronicles",
    nome: "1 Crônicas",
    nomeIngles: "1 chronicles",
    capitulos: 29,
  },
  {
    id: "2-chronicles",
    nome: "2 Crônicas",
    nomeIngles: "2 chronicles",
    capitulos: 36,
  },
  { id: "ezra", nome: "Esdras", nomeIngles: "ezra", capitulos: 10 },
  { id: "nehemiah", nome: "Neemias", nomeIngles: "nehemiah", capitulos: 13 },
  { id: "esther", nome: "Ester", nomeIngles: "esther", capitulos: 10 },
  { id: "job", nome: "Jó", nomeIngles: "job", capitulos: 42 },
  { id: "psalms", nome: "Salmos", nomeIngles: "psalms", capitulos: 150 },
  { id: "proverbs", nome: "Provérbios", nomeIngles: "proverbs", capitulos: 31 },
  {
    id: "ecclesiastes",
    nome: "Eclesiastes",
    nomeIngles: "ecclesiastes",
    capitulos: 12,
  },
  {
    id: "song-of-solomon",
    nome: "Cânticos",
    nomeIngles: "song of solomon",
    capitulos: 8,
  },
  { id: "isaiah", nome: "Isaías", nomeIngles: "isaiah", capitulos: 66 },
  { id: "jeremiah", nome: "Jeremias", nomeIngles: "jeremiah", capitulos: 52 },
  {
    id: "lamentations",
    nome: "Lamentações",
    nomeIngles: "lamentations",
    capitulos: 5,
  },
  { id: "ezekiel", nome: "Ezequiel", nomeIngles: "ezekiel", capitulos: 48 },
  { id: "daniel", nome: "Daniel", nomeIngles: "daniel", capitulos: 12 },
  { id: "hosea", nome: "Oséias", nomeIngles: "hosea", capitulos: 14 },
  { id: "joel", nome: "Joel", nomeIngles: "joel", capitulos: 3 },
  { id: "amos", nome: "Amós", nomeIngles: "amos", capitulos: 9 },
  { id: "obadiah", nome: "Obadias", nomeIngles: "obadiah", capitulos: 1 },
  { id: "jonah", nome: "Jonas", nomeIngles: "jonah", capitulos: 4 },
  { id: "micah", nome: "Miquéias", nomeIngles: "micah", capitulos: 7 },
  { id: "nahum", nome: "Naum", nomeIngles: "nahum", capitulos: 3 },
  { id: "habakkuk", nome: "Habacuque", nomeIngles: "habakkuk", capitulos: 3 },
  { id: "zephaniah", nome: "Sofonias", nomeIngles: "zephaniah", capitulos: 3 },
  { id: "haggai", nome: "Ageu", nomeIngles: "haggai", capitulos: 2 },
  { id: "zechariah", nome: "Zacarias", nomeIngles: "zechariah", capitulos: 14 },
  { id: "malachi", nome: "Malaquias", nomeIngles: "malachi", capitulos: 4 },

  // Novo Testamento
  { id: "matthew", nome: "Mateus", nomeIngles: "matthew", capitulos: 28 },
  { id: "mark", nome: "Marcos", nomeIngles: "mark", capitulos: 16 },
  { id: "luke", nome: "Lucas", nomeIngles: "luke", capitulos: 24 },
  { id: "john", nome: "João", nomeIngles: "john", capitulos: 21 },
  { id: "acts", nome: "Atos", nomeIngles: "acts", capitulos: 28 },
  { id: "romans", nome: "Romanos", nomeIngles: "romans", capitulos: 16 },
  {
    id: "1-corinthians",
    nome: "1 Coríntios",
    nomeIngles: "1 corinthians",
    capitulos: 16,
  },
  {
    id: "2-corinthians",
    nome: "2 Coríntios",
    nomeIngles: "2 corinthians",
    capitulos: 13,
  },
  { id: "galatians", nome: "Gálatas", nomeIngles: "galatians", capitulos: 6 },
  { id: "ephesians", nome: "Efésios", nomeIngles: "ephesians", capitulos: 6 },
  {
    id: "philippians",
    nome: "Filipenses",
    nomeIngles: "philippians",
    capitulos: 4,
  },
  {
    id: "colossians",
    nome: "Colossenses",
    nomeIngles: "colossians",
    capitulos: 4,
  },
  {
    id: "1-thessalonians",
    nome: "1 Tessalonicenses",
    nomeIngles: "1 thessalonians",
    capitulos: 5,
  },
  {
    id: "2-thessalonians",
    nome: "2 Tessalonicenses",
    nomeIngles: "2 thessalonians",
    capitulos: 3,
  },
  { id: "1-timothy", nome: "1 Timóteo", nomeIngles: "1 timothy", capitulos: 6 },
  { id: "2-timothy", nome: "2 Timóteo", nomeIngles: "2 timothy", capitulos: 4 },
  { id: "titus", nome: "Tito", nomeIngles: "titus", capitulos: 3 },
  { id: "philemon", nome: "Filemom", nomeIngles: "philemon", capitulos: 1 },
  { id: "hebrews", nome: "Hebreus", nomeIngles: "hebrews", capitulos: 13 },
  { id: "james", nome: "Tiago", nomeIngles: "james", capitulos: 5 },
  { id: "1-peter", nome: "1 Pedro", nomeIngles: "1 peter", capitulos: 5 },
  { id: "2-peter", nome: "2 Pedro", nomeIngles: "2 peter", capitulos: 3 },
  { id: "1-john", nome: "1 João", nomeIngles: "1 john", capitulos: 5 },
  { id: "2-john", nome: "2 João", nomeIngles: "2 john", capitulos: 1 },
  { id: "3-john", nome: "3 João", nomeIngles: "3 john", capitulos: 1 },
  { id: "jude", nome: "Judas", nomeIngles: "jude", capitulos: 1 },
  {
    id: "revelation",
    nome: "Apocalipse",
    nomeIngles: "revelation",
    capitulos: 22,
  },
];

export const versoes = [
  { id: "kjv", nome: "King James Version" },
  { id: "bbe", nome: "Bíblia em Inglês Básico" },
];
